# T1 = ("Hello","mello")
# print(T1)
# x= list(T1)
# print(x)
# x.append("wow")
# print(x)
# T1 =tuple(x)
# print(T1)
T1 = ('apple',24,[3.5],'monday')
x = list(T1)
x.append('tuesday')
T1 = tuple(x)
print(T1)